name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive  # Fetch the Docsy theme
          fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.74.3"
          extended: true

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: v14.x

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - run: ls
      - run: hugo --minify -t docsy

        #- name: Build site
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        #run: hugo -t docsy --config ./config.toml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master # to master
          publish_dir: ./public # from public
